#!/bin/bash

job_prefix="jovs"
juju_controller_name="${job_prefix}-cloud"
juju_model_arg="-m ${juju_controller_name}:default"

poolname="${job_prefix}images"
net_driver=${net_driver:-e1000}
nname="$job_prefix"
# bird daemon configured to this CIDR on KVM
addr="10.0.0"
nname_ext="${job_prefix}_ext"
addr_ext="10.0.1"

mac_base='52:54:00:10:00'
mac_base_ext='52:54:00:11:00'
# juju controller
cont_idx='99'
# openstack components (controllers + rabbit + db)
os_cont_0_idx='10'
# network nodes
os_net_1_idx='20'
os_net_2_idx='21'
os_net_3_idx='22'
# openstack compute
os_comp_1_idx='30'
os_comp_2_idx='31'

# openstack definitions
public_network_addr="10.10.0"
# Neutron
brex_iface='br-ex'
brex_port='dummy0'
