#!/bin/bash

# definitions for KVM/virsh:

export LIBVIRT_DEFAULT_URI=qemu:///system
virsh_cmd="virsh"

# base image for VMs is a ubuntu cloud image with:
# 1) removed cloud-init (echo 'datasource_list: [ None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg ; sudo apt-get purge cloud-init ; sudo rm -rf /etc/cloud/; sudo rm -rf /var/lib/cloud/ )
# 2) added jenkins's key to authorized keys for ubuntu user
# 3) added password '123' for user ubuntu
# 4) root disk resized to 60G ( truncate -s 60G temp.raw ; virt-resize --expand /dev/vda1 ubuntu-xenial.qcow2 temp.raw ; qemu-img convert -O qcow2 temp.raw ubuntu-xenial-new.qcow2 )
# step 1-3 can be done for mounted image
BASE_IMAGE_NAME=${BASE_IMAGE_NAME:-"ubuntu-$SERIES.qcow2"}
BASE_IMAGE_DIR=${BASE_IMAGE_DIR:-'/home/root/images'}
BASE_IMAGE="${BASE_IMAGE_DIR}/${BASE_IMAGE_NAME}"

# KVM helpers

function delete_network() {
  local network_name="$1"
  $virsh_cmd net-destroy $network_name 2> /dev/null || true
  $virsh_cmd net-undefine $network_name 2> /dev/null || true
}

function create_network() {
  local network_name="$1"
  local addr="$2"

  delete_network $network_name

  echo "<network><name>$network_name</name><forward mode=\"nat\"><nat><port start=\"1024\" end=\"65535\"/></nat></forward><ip address=\"$addr.1\" netmask=\"255.255.255.0\"><dhcp><range start=\"$addr.100\" end=\"$addr.129\"/></dhcp></ip></network>" > /tmp/juju-net.xml
  $virsh_cmd net-define /tmp/juju-net.xml
  rm /tmp/juju-net.xml
  $virsh_cmd net-autostart $network_name
  $virsh_cmd -c qemu:///system net-start $network_name
}

function create_pool() {
  local poolname="$1"
  local path="$HOME/libvirt/$poolname"
  # pre-create path if absent to save ownership
  mkdir -p "$path"
  $virsh_cmd pool-define-as $poolname dir - - - - "$path"
  $virsh_cmd pool-build $poolname
  $virsh_cmd pool-start $poolname
  $virsh_cmd pool-autostart $poolname
}

function delete_pool() {
  local poolname="$1"
  local path=`get_pool_path $poolname`
  $virsh_cmd pool-destroy $poolname
  $virsh_cmd pool-undefine $poolname
  rm -rf "$poolpath" || /bin/true
}

function get_pool_path() {
  local poolname=$1
  $virsh_cmd pool-info $poolname &>/dev/null || return
  $virsh_cmd pool-dumpxml $poolname | sed -n '/path/{s/.*<path>\(.*\)<\/path>.*/\1/;p}'
}

function delete_domains() {
  for name in `$virsh_cmd list --all | grep "${job_prefix}-" | awk '{print $2}'` ; do
    $virsh_cmd destroy $name || /bin/true
    sleep 2
    $virsh_cmd undefine $name || /bin/true
  done
}

function delete_volume() {
  volname=$1
  poolname=$2
  pool_path=$(get_pool_path $poolname)
  $virsh_cmd vol-delete $volname --pool $poolname 2>/dev/null || rm -f $pool_path/$volname 2>/dev/null
}
